//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Oxygene Version: 5.0.28.842
//     Runtime Version: 4.0.30319.225
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE CW3}
{$HIDE PW12}

namespace RemObjects.Script.Properties;

interface

uses
    System;
    
type
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [System.CodeDom.Compiler.GeneratedCodeAttribute('System.Resources.Tools.StronglyTypedResourceBuilder', '4.0.0.0')]
    [System.Diagnostics.DebuggerNonUserCodeAttribute]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
    Resources = class
    private 
        class var resourceMan: System.Resources.ResourceManager;
        class var resourceCulture: System.Globalization.CultureInfo;
        class method get_ResourceManager: System.Resources.ResourceManager;
        class method get_Culture: System.Globalization.CultureInfo;
        class method set_Culture(value: System.Globalization.CultureInfo);
        class method get_Ambigious_overloaded_method_0_with_1_parameters: System.String;
        class method get_eAlreadyRunning: System.String;
        class method get_eBeginExpected: System.String;
        class method get_eCannotAssignValueToExpression: System.String;
        class method get_eCannotBreakHere: System.String;
        class method get_eCannotContinueHere: System.String;
        class method get_eCannotReturnHere: System.String;
        class method get_eCatchOrFinallyExpected: System.String;
        class method get_eClosingBraceExpected: System.String;
        class method get_eClosingBracketExpected: System.String;
        class method get_eClosingParenthesisExpected: System.String;
        class method get_eColonExpected: System.String;
        class method get_eCommentError: System.String;
        class method get_eDoExpected: System.String;
        class method get_eDotExpected: System.String;
        class method get_eDuplicateIdentifier: System.String;
        class method get_eDuplicateLabel: System.String;
        class method get_eEndExpected: System.String;
        class method get_eEOFInRegex: System.String;
        class method get_eEOFInString: System.String;
        class method get_eEqualExpected: System.String;
        class method get_eErrorInCharacter: System.String;
        class method get_eFatalErrorWhileCompiling: System.String;
        class method get_eFinallyExceptExpected: System.String;
        class method get_eIdentifierExpected: System.String;
        class method get_eImplementationExpected: System.String;
        class method get_eInterfaceExpected: System.String;
        class method get_eInternalError: System.String;
        class method get_eInvalidEscapeSequence: System.String;
        class method get_eNoSuchFunction: System.String;
        class method get_eNotAFunction: System.String;
        class method get_eOfExpected: System.String;
        class method get_eOnlyOneDefaultAllowed: System.String;
        class method get_eOnlyOneVariableAllowed: System.String;
        class method get_eOpeningBraceExpected: System.String;
        class method get_eOpeningParenthesisExpected: System.String;
        class method get_eRunInThreadCannotBeModifiedWhenScriptIsRunning: System.String;
        class method get_eRuntimeUncaughtReference: System.String;
        class method get_eSemicolonExpected: System.String;
        class method get_eSyntaxError: System.String;
        class method get_eThenExpected: System.String;
        class method get_eToDowntoExpected: System.String;
        class method get_eUnexpectedEndOfFile: System.String;
        class method get_eUnknownCharacter: System.String;
        class method get_eUnknownLabelTarget: System.String;
        class method get_eUntilExpected: System.String;
        class method get_eWhileExpected: System.String;
        class method get_eWithNotAllowedInStrict: System.String;
        class method get_No_overloaded_method_0_with_1_parameters: System.String;
    assembly 
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        class property ResourceManager: System.Resources.ResourceManager read get_ResourceManager;
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        class property Culture: System.Globalization.CultureInfo read get_Culture write set_Culture;
        class property Ambigious_overloaded_method_0_with_1_parameters: System.String read get_Ambigious_overloaded_method_0_with_1_parameters;
        class property eAlreadyRunning: System.String read get_eAlreadyRunning;
        class property eBeginExpected: System.String read get_eBeginExpected;
        class property eCannotAssignValueToExpression: System.String read get_eCannotAssignValueToExpression;
        class property eCannotBreakHere: System.String read get_eCannotBreakHere;
        class property eCannotContinueHere: System.String read get_eCannotContinueHere;
        class property eCannotReturnHere: System.String read get_eCannotReturnHere;
        class property eCatchOrFinallyExpected: System.String read get_eCatchOrFinallyExpected;
        class property eClosingBraceExpected: System.String read get_eClosingBraceExpected;
        class property eClosingBracketExpected: System.String read get_eClosingBracketExpected;
        class property eClosingParenthesisExpected: System.String read get_eClosingParenthesisExpected;
        class property eColonExpected: System.String read get_eColonExpected;
        class property eCommentError: System.String read get_eCommentError;
        class property eDoExpected: System.String read get_eDoExpected;
        class property eDotExpected: System.String read get_eDotExpected;
        class property eDuplicateIdentifier: System.String read get_eDuplicateIdentifier;
        class property eDuplicateLabel: System.String read get_eDuplicateLabel;
        class property eEndExpected: System.String read get_eEndExpected;
        class property eEOFInRegex: System.String read get_eEOFInRegex;
        class property eEOFInString: System.String read get_eEOFInString;
        class property eEqualExpected: System.String read get_eEqualExpected;
        class property eErrorInCharacter: System.String read get_eErrorInCharacter;
        class property eFatalErrorWhileCompiling: System.String read get_eFatalErrorWhileCompiling;
        class property eFinallyExceptExpected: System.String read get_eFinallyExceptExpected;
        class property eIdentifierExpected: System.String read get_eIdentifierExpected;
        class property eImplementationExpected: System.String read get_eImplementationExpected;
        class property eInterfaceExpected: System.String read get_eInterfaceExpected;
        class property eInternalError: System.String read get_eInternalError;
        class property eInvalidEscapeSequence: System.String read get_eInvalidEscapeSequence;
        class property eNoSuchFunction: System.String read get_eNoSuchFunction;
        class property eNotAFunction: System.String read get_eNotAFunction;
        class property eOfExpected: System.String read get_eOfExpected;
        class property eOnlyOneDefaultAllowed: System.String read get_eOnlyOneDefaultAllowed;
        class property eOnlyOneVariableAllowed: System.String read get_eOnlyOneVariableAllowed;
        class property eOpeningBraceExpected: System.String read get_eOpeningBraceExpected;
        class property eOpeningParenthesisExpected: System.String read get_eOpeningParenthesisExpected;
        class property eRunInThreadCannotBeModifiedWhenScriptIsRunning: System.String read get_eRunInThreadCannotBeModifiedWhenScriptIsRunning;
        class property eRuntimeUncaughtReference: System.String read get_eRuntimeUncaughtReference;
        class property eSemicolonExpected: System.String read get_eSemicolonExpected;
        class property eSyntaxError: System.String read get_eSyntaxError;
        class property eThenExpected: System.String read get_eThenExpected;
        class property eToDowntoExpected: System.String read get_eToDowntoExpected;
        class property eUnexpectedEndOfFile: System.String read get_eUnexpectedEndOfFile;
        class property eUnknownCharacter: System.String read get_eUnknownCharacter;
        class property eUnknownLabelTarget: System.String read get_eUnknownLabelTarget;
        class property eUntilExpected: System.String read get_eUntilExpected;
        class property eWhileExpected: System.String read get_eWhileExpected;
        class property eWithNotAllowedInStrict: System.String read get_eWithNotAllowedInStrict;
        class property No_overloaded_method_0_with_1_parameters: System.String read get_No_overloaded_method_0_with_1_parameters;
    assembly and protected 
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute('Microsoft.Performance', 'CA1811:AvoidUncalledPrivateCode')]
        constructor;
end;

implementation

{ Resources }

constructor Resources;
begin
end;

class method Resources.get_ResourceManager: System.Resources.ResourceManager;
begin
    if System.Object.ReferenceEquals(resourceMan, nil) then begin
        var temp: System.Resources.ResourceManager := new System.Resources.ResourceManager('RemObjects.Script.Properties.Resources', typeOf(Resources).Assembly);
        resourceMan := temp;
    end;
    exit(resourceMan);
end;

class method Resources.get_Culture: System.Globalization.CultureInfo;
begin
    exit(resourceCulture);
end;

class method Resources.set_Culture(value: System.Globalization.CultureInfo);
begin
    resourceCulture := value;
end;

class method Resources.get_Ambigious_overloaded_method_0_with_1_parameters: System.String;
begin
    exit(ResourceManager.GetString('Ambigious_overloaded_method_0_with_1_parameters', resourceCulture));
end;

class method Resources.get_eAlreadyRunning: System.String;
begin
    exit(ResourceManager.GetString('eAlreadyRunning', resourceCulture));
end;

class method Resources.get_eBeginExpected: System.String;
begin
    exit(ResourceManager.GetString('eBeginExpected', resourceCulture));
end;

class method Resources.get_eCannotAssignValueToExpression: System.String;
begin
    exit(ResourceManager.GetString('eCannotAssignValueToExpression', resourceCulture));
end;

class method Resources.get_eCannotBreakHere: System.String;
begin
    exit(ResourceManager.GetString('eCannotBreakHere', resourceCulture));
end;

class method Resources.get_eCannotContinueHere: System.String;
begin
    exit(ResourceManager.GetString('eCannotContinueHere', resourceCulture));
end;

class method Resources.get_eCannotReturnHere: System.String;
begin
    exit(ResourceManager.GetString('eCannotReturnHere', resourceCulture));
end;

class method Resources.get_eCatchOrFinallyExpected: System.String;
begin
    exit(ResourceManager.GetString('eCatchOrFinallyExpected', resourceCulture));
end;

class method Resources.get_eClosingBraceExpected: System.String;
begin
    exit(ResourceManager.GetString('eClosingBraceExpected', resourceCulture));
end;

class method Resources.get_eClosingBracketExpected: System.String;
begin
    exit(ResourceManager.GetString('eClosingBracketExpected', resourceCulture));
end;

class method Resources.get_eClosingParenthesisExpected: System.String;
begin
    exit(ResourceManager.GetString('eClosingParenthesisExpected', resourceCulture));
end;

class method Resources.get_eColonExpected: System.String;
begin
    exit(ResourceManager.GetString('eColonExpected', resourceCulture));
end;

class method Resources.get_eCommentError: System.String;
begin
    exit(ResourceManager.GetString('eCommentError', resourceCulture));
end;

class method Resources.get_eDoExpected: System.String;
begin
    exit(ResourceManager.GetString('eDoExpected', resourceCulture));
end;

class method Resources.get_eDotExpected: System.String;
begin
    exit(ResourceManager.GetString('eDotExpected', resourceCulture));
end;

class method Resources.get_eDuplicateIdentifier: System.String;
begin
    exit(ResourceManager.GetString('eDuplicateIdentifier', resourceCulture));
end;

class method Resources.get_eDuplicateLabel: System.String;
begin
    exit(ResourceManager.GetString('eDuplicateLabel', resourceCulture));
end;

class method Resources.get_eEndExpected: System.String;
begin
    exit(ResourceManager.GetString('eEndExpected', resourceCulture));
end;

class method Resources.get_eEOFInRegex: System.String;
begin
    exit(ResourceManager.GetString('eEOFInRegex', resourceCulture));
end;

class method Resources.get_eEOFInString: System.String;
begin
    exit(ResourceManager.GetString('eEOFInString', resourceCulture));
end;

class method Resources.get_eEqualExpected: System.String;
begin
    exit(ResourceManager.GetString('eEqualExpected', resourceCulture));
end;

class method Resources.get_eErrorInCharacter: System.String;
begin
    exit(ResourceManager.GetString('eErrorInCharacter', resourceCulture));
end;

class method Resources.get_eFatalErrorWhileCompiling: System.String;
begin
    exit(ResourceManager.GetString('eFatalErrorWhileCompiling', resourceCulture));
end;

class method Resources.get_eFinallyExceptExpected: System.String;
begin
    exit(ResourceManager.GetString('eFinallyExceptExpected', resourceCulture));
end;

class method Resources.get_eIdentifierExpected: System.String;
begin
    exit(ResourceManager.GetString('eIdentifierExpected', resourceCulture));
end;

class method Resources.get_eImplementationExpected: System.String;
begin
    exit(ResourceManager.GetString('eImplementationExpected', resourceCulture));
end;

class method Resources.get_eInterfaceExpected: System.String;
begin
    exit(ResourceManager.GetString('eInterfaceExpected', resourceCulture));
end;

class method Resources.get_eInternalError: System.String;
begin
    exit(ResourceManager.GetString('eInternalError', resourceCulture));
end;

class method Resources.get_eInvalidEscapeSequence: System.String;
begin
    exit(ResourceManager.GetString('eInvalidEscapeSequence', resourceCulture));
end;

class method Resources.get_eNoSuchFunction: System.String;
begin
    exit(ResourceManager.GetString('eNoSuchFunction', resourceCulture));
end;

class method Resources.get_eNotAFunction: System.String;
begin
    exit(ResourceManager.GetString('eNotAFunction', resourceCulture));
end;

class method Resources.get_eOfExpected: System.String;
begin
    exit(ResourceManager.GetString('eOfExpected', resourceCulture));
end;

class method Resources.get_eOnlyOneDefaultAllowed: System.String;
begin
    exit(ResourceManager.GetString('eOnlyOneDefaultAllowed', resourceCulture));
end;

class method Resources.get_eOnlyOneVariableAllowed: System.String;
begin
    exit(ResourceManager.GetString('eOnlyOneVariableAllowed', resourceCulture));
end;

class method Resources.get_eOpeningBraceExpected: System.String;
begin
    exit(ResourceManager.GetString('eOpeningBraceExpected', resourceCulture));
end;

class method Resources.get_eOpeningParenthesisExpected: System.String;
begin
    exit(ResourceManager.GetString('eOpeningParenthesisExpected', resourceCulture));
end;

class method Resources.get_eRunInThreadCannotBeModifiedWhenScriptIsRunning: System.String;
begin
    exit(ResourceManager.GetString('eRunInThreadCannotBeModifiedWhenScriptIsRunning', resourceCulture));
end;

class method Resources.get_eRuntimeUncaughtReference: System.String;
begin
    exit(ResourceManager.GetString('eRuntimeUncaughtReference', resourceCulture));
end;

class method Resources.get_eSemicolonExpected: System.String;
begin
    exit(ResourceManager.GetString('eSemicolonExpected', resourceCulture));
end;

class method Resources.get_eSyntaxError: System.String;
begin
    exit(ResourceManager.GetString('eSyntaxError', resourceCulture));
end;

class method Resources.get_eThenExpected: System.String;
begin
    exit(ResourceManager.GetString('eThenExpected', resourceCulture));
end;

class method Resources.get_eToDowntoExpected: System.String;
begin
    exit(ResourceManager.GetString('eToDowntoExpected', resourceCulture));
end;

class method Resources.get_eUnexpectedEndOfFile: System.String;
begin
    exit(ResourceManager.GetString('eUnexpectedEndOfFile', resourceCulture));
end;

class method Resources.get_eUnknownCharacter: System.String;
begin
    exit(ResourceManager.GetString('eUnknownCharacter', resourceCulture));
end;

class method Resources.get_eUnknownLabelTarget: System.String;
begin
    exit(ResourceManager.GetString('eUnknownLabelTarget', resourceCulture));
end;

class method Resources.get_eUntilExpected: System.String;
begin
    exit(ResourceManager.GetString('eUntilExpected', resourceCulture));
end;

class method Resources.get_eWhileExpected: System.String;
begin
    exit(ResourceManager.GetString('eWhileExpected', resourceCulture));
end;

class method Resources.get_eWithNotAllowedInStrict: System.String;
begin
    exit(ResourceManager.GetString('eWithNotAllowedInStrict', resourceCulture));
end;

class method Resources.get_No_overloaded_method_0_with_1_parameters: System.String;
begin
    exit(ResourceManager.GetString('No_overloaded_method_0_with_1_parameters', resourceCulture));
end;

end.
