//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Oxygene Version: 3.0.0.1
//     Runtime Version: 2.0.50727.3074
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
{$HIDE CW3}
{$HIDE PW12}

namespace RemObjects.Script.Properties;

interface

type
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
    [System.CodeDom.Compiler.GeneratedCodeAttribute('Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator', '9.0.0.0')]
    Settings = partial sealed class(System.Configuration.ApplicationSettingsBase)
        private 
            class var defaultInstance: Settings := (System.Configuration.ApplicationSettingsBase.Synchronized(new Settings()) as Settings);
            class method get_Default: Settings;
        public 
            class property Default: Settings read get_Default;
    end;
    
implementation

{ Settings }

class method Settings.get_Default: Settings;
begin
    exit(defaultInstance);
end;

end.
